---
# create a registry
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5005

---
# create a cluster
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: devspace-demo
  networking:
    apiServerAddress: "127.0.0.1"
    apiServerPort: 4443
  nodes:
    - role: control-plane
    - role: worker
    - role: worker
