# check Dockerfile for production version of dockefile
FROM golang:1.18-alpine

WORKDIR /app

COPY go.mod ./
# COPY go.sum ./
# RUN go mod download

COPY *.go ./

RUN go build -o /api

# air to relod the code
# ref: https://github.com/cosmtrek/air
RUN apk update && apk add curl && curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s

EXPOSE 8080

CMD [ "/api" ]
